package Example;


/**
* Example/Echo.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from ../echo.idl
* Thursday, October 22, 2015 12:24:36 AM CST
*/

public interface Echo extends EchoOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface Echo
